### ISSUE TITLE
有关点状信号参数和非各项同性数据处理的问题

### ISSUE THREAD

**Issue by zxy126** [fangchunyu/CACS-Demo#1]
你好，感谢您的CACS文章和代码。暂时已成功跑通了测试数据集。

但是在测试我自己的数据前有些小问题想请教一下。

1. 在文章附件写到点状信号k = -0.08 and b = 0.52，线状信号k = -0.35 and b= 1.82。
 > k = -0.08 and b = 0.52 for point-like signals, such as cell nuclei, and k = -0.35 and b= 1.82 for line-like signals

但是在CACS.m的注释中写着thy1（线状）的参数为k = -0.08 and b = 0.52
 > k = if contains(filename, 'thy1')，k1 = -0.085;b1 = 0.5199;

请问应该以何处为准

2. 我们使用的光片z轴分辨率只有xy的一半，采样率设置较低。是否可以直接使用CACS.m处理，还是说需要对z轴进行插值或者额外采样处理。

非常感谢

**Comment by fangchunyu** [comment]
你好，

1.我建议以论文的设置为准，可能当时写注释的时候存在纰漏，但是论文数据前后验证了多次，应当不存在问题。但如果你自己的数据测试结果不好，可以试试设置其他的k和b，甚至跑个循环去遍历。
因为这个k和b本就是在尝试大量的数据之后拟合出来的，对部分特殊数据存在不适配属于正常现象。

2.写代码的时候兼容各种类型的分辨率，不用插值。不要求数据一定isotropic。


谢谢

________________________________
发件人: Chen jierui ***@***.***>
发送时间: 2024年2月2日 20:26
收件人: fangchunyu/CACS-Demo ***@***.***>
抄送: Subscribed ***@***.***>
主题: [fangchunyu/CACS-Demo] 有关点状信号参数和非各项同性数据处理的问题 (Issue #1)


你好，感谢您的CACS文章和代码。暂时已成功跑通了测试数据集。

但是在测试我自己的数据前有些小问题想请教一下。

  1.  在文章附件写到点状信号k = -0.08 and b = 0.52，线状信号k = -0.35 and b= 1.82。

k = -0.08 and b = 0.52 for point-like signals, such as cell nuclei, and k = -0.35 and b= 1.82 for line-like signals

但是在CACS.m的注释中写着thy1（线状）的参数为k = -0.08 and b = 0.52

k = if contains(filename, 'thy1')，k1 = -0.085;b1 = 0.5199;

请问应该以何处为准

  1.  我们使用的光片z轴分辨率只有xy的一半，采样率设置较低。是否可以直接使用CACS.m处理，还是说需要对z轴进行插值或者额外采样处理。

非常感谢

―
